apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: 5pypython
  janus-idp.io/tekton: 5pypython
  backstage.io/kubernetes-id: 5pypython
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 5pypython
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
